# Generated by Django 4.2.2 on 2023-06-24 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tution', '0002_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.CharField(default=models.CharField(max_length=101), max_length=100),
        ),
    ]
