# Generated by Django 4.2.2 on 2023-06-25 07:10

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tution', '0005_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='medium',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('bangla', 'bangla'), ('english', 'english'), ('arabic', 'arabic')], default='bangla', max_length=100),
        ),
    ]
